"""Chart helpers for the analysis sandbox.

Thin wrappers over plotly.express with one consistent style, so charts
generated by the agent share a single look instead of each turn inventing
its own defaults. Helpers save the figure as a JSON spec — no server-side
rendering is needed — and the Streamlit UI re-renders it interactively with
st.plotly_chart, re-tinting chrome and categorical colors for the active
app theme.

Palette rules (validated for color-vision safety, both surfaces):
- Categorical hues are assigned in fixed order, never cycled: beyond the
  eight slots, fold extra series into "Other" instead of wrapping.
- Sequential encoding uses the blue ramp, light -> dark.
- Status colors (good/warning/serious/critical) are reserved for status
  and never reused as series colors.
"""

from __future__ import annotations

from pathlib import Path

import plotly.express as px
from plotly import graph_objects as go

LIGHT_CATEGORICAL = [
    "#2a78d6",
    "#eb6834",
    "#1baf7a",
    "#eda100",
    "#e87ba4",
    "#008300",
    "#4a3aa7",
    "#e34948",
]
DARK_CATEGORICAL = [
    "#3987e5",
    "#d95926",
    "#199e70",
    "#c98500",
    "#d55181",
    "#008300",
    "#9085e9",
    "#e66767",
]

# Chart chrome: ink, gridlines, baselines per surface.
LIGHT_CHROME = {
    "primary": "#0b0b0b",
    "secondary": "#52514e",
    "muted": "#898781",
    "gridline": "#e1e0d9",
    "baseline": "#c3c2b7",
}
DARK_CHROME = {
    "primary": "#ffffff",
    "secondary": "#c3c2b7",
    "muted": "#898781",
    "gridline": "#2c2c2a",
    "baseline": "#383835",
}

_FONT = "'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif"


def _style(fig: go.Figure, title: str, chrome: dict) -> go.Figure:
    """Apply the shared look: transparent surface, recessive axes, clean ink.

    Margins are computed from what the figure contains so axis titles, tick
    labels, and legends stay inside the frame; plotly.js's automargin
    expands them further when tick labels need the room.
    """
    xaxis, yaxis = fig.layout.xaxis, fig.layout.yaxis
    xaxis.automargin = True
    yaxis.automargin = True
    has_legend = fig.layout.showlegend is not False and len(fig.data) > 1
    if has_legend:
        fig.update_layout(
            legend={
                "orientation": "h",
                "xanchor": "right",
                "x": 1,
                "yanchor": "bottom",
                "y": 1.02,
                "font": {"color": chrome["secondary"]},
            }
        )
    fig.update_layout(
        title={"text": title, "font": {"color": chrome["primary"], "size": 16}},
        template=None,
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font={"family": _FONT, "color": chrome["muted"]},
        hoverlabel={"font": {"family": _FONT}},
        margin={
            "l": 64 if yaxis.title.text else 8,
            "r": 8,
            "t": (44 if title else 8) + (32 if has_legend else 0),
            "b": 52 if xaxis.title.text else 8,
        },
    )
    for axis in ("xaxis", "yaxis"):
        fig.layout[axis].gridcolor = chrome["gridline"]
        fig.layout[axis].zerolinecolor = chrome["baseline"]
        fig.layout[axis].linecolor = chrome["baseline"]
    return fig


def save(fig: go.Figure, path: str | Path) -> Path:
    """Persist a figure as JSON; returns the resolved path."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    fig.write_json(target)
    return target


def _finish(fig: go.Figure, title: str, path: str | Path | None) -> go.Figure:
    styled = _style(fig, title, LIGHT_CHROME)
    if path:
        save(styled, path)
    return styled


def bar(
    df, x, y, title: str = "", path: str | Path | None = None, **kwargs
) -> go.Figure:
    """Vertical bar chart of `df`; extra kwargs go to plotly.express.bar."""
    fig = px.bar(df, x=x, y=y, color_discrete_sequence=LIGHT_CATEGORICAL, **kwargs)
    fig.update_layout(bargap=0.2)
    return _finish(fig, title, path)


def line(
    df, x, y, title: str = "", path: str | Path | None = None, **kwargs
) -> go.Figure:
    """Line chart of `df`; extra kwargs go to plotly.express.line."""
    fig = px.line(df, x=x, y=y, color_discrete_sequence=LIGHT_CATEGORICAL, **kwargs)
    fig.update_traces(line={"width": 2})
    return _finish(fig, title, path)


def scatter(
    df, x, y, title: str = "", path: str | Path | None = None, **kwargs
) -> go.Figure:
    """Scatter plot of `df`; extra kwargs go to plotly.express.scatter."""
    fig = px.scatter(df, x=x, y=y, color_discrete_sequence=LIGHT_CATEGORICAL, **kwargs)
    fig.update_traces(marker={"size": 9})
    return _finish(fig, title, path)
